services:
  app:
    image: ghcr.io/adminvpshub/ais-terminal:latest
    ports:
      - "3000:3001"
    env_file: .env
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: always
